apiVersion: v1
data:
  index.html: |-
    <html>
    <head>
        <!--<meta charset="UTF-8">-->
        <meta charset="UTF-8">
    </head>
    <body>
    <h1>Тестовая страница</h1>
    <p>V2 Простая тестовая страница, для видео на <a href="https://www.youtube.com/channel/UCU55LZT7oRxhX4GTvb5H4HA">
        моём канале</a>.
    </p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: index-html

